constraint: constraints/cloudbuild.useBuildServiceAccount
listPolicy:
  allowAll: false
  allowedValues:
  - projects/agape-sovereign/serviceAccounts/firebase-build-sa@agape-sovereign.iam.gserviceaccount.com
